# Generated by Django 4.0.1 on 2022-02-27 04:07

from django.db import migrations


def apply_migration(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("accounts", "Profile")

    users = User.objects.filter(profile__isnull=True)
    for user in users:
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_alter_profile_about_me_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RunPython(
            apply_migration,
            migrations.RunPython.noop
        )
    ]
