# Generated by Django 4.0.1 on 2022-01-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.statusmodel', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='issuemodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.typemodel', verbose_name='Тип'),
        ),
    ]
