# Generated by Django 4.0.1 on 2022-01-19 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_issuemodel_type_issuemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='summary',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Заголовок'),
        ),
    ]
