# Generated by Django 4.0.1 on 2022-02-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_issuemodel_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('started', models.DateField(blank=True, verbose_name='Дата начала')),
                ('finished', models.DateField(null=True, verbose_name='Дата окончания')),
            ],
        ),
    ]
