# Generated by Django 4.0.1 on 2022-02-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_projectmodel_options_alter_projectmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='project',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='webapp.projectmodel', verbose_name='Проект'),
        ),
    ]
