# Generated by Django 4.0.1 on 2022-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_issuemodel_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='finished',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='started',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
