# Generated by Django 4.0.1 on 2022-02-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_projectmodel_user_projectmodel_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuemodel',
            options={'permissions': (('add_issue_in_own_poject', 'Добавлять задачи в свой проект'), ('change_issue_in_own_project', 'Изменять задачи в своем проекте'), ('delete_issue_in_own_project', 'Удалять задачи в своем проекте')), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'permissions': (('change_user_in_own_project', 'Изменять список пользователей в своем проекте'),), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
